#!/usr/bin/env python3

import sys
import os
import protontricks
from pathlib import Path
import vdf
import subprocess

# This script adds the launch argument exe of the selected Steam shortcut.
#
# This is useful when you add an installer to steam to run under proton and then
# after installing you want to update the steam shortcut to use the actual game
# instead of the installer.
#
# Usage:
# - Add example_game_installer.exe to steam
# - Install game by running it under proton
# - Locate the installed game
# - Run this script with the example_game.exe path as argument
#
# Requires protontricks

if len(sys.argv) != 2:
    print("Expected one launch argument")
    exit(1)

program = os.path.abspath(sys.argv[1])

if not os.path.exists(program):
    print("Program does not exist: " + program)
    exit(1)

steam_path = (Path.home() / ".steam" / "steam").resolve()

steamid3 = protontricks.find_current_steamid3(steam_path)
shortcuts_path = steam_path / "userdata" / str(steamid3) / "config" / "shortcuts.vdf"

content = shortcuts_path.read_bytes()
vdf_data = protontricks.lower_dict(vdf.binary_loads(content, raise_on_remaining=False))

apps = []
for shortcut_id, shortcut_data in vdf_data["shortcuts"].items():
    apps.append(shortcut_data["appname"])

result = subprocess.run(["zenity", "--list", "--column", "'Steam App'"] + apps, stdout=subprocess.PIPE)
choice = str(result.stdout)[:-3][2:]

for shortcut_id, shortcut_data in vdf_data["shortcuts"].items():
    if shortcut_data["appname"] == choice:
        shortcut_data["exe"] = "\"" + program + "\""
        shortcut_data["startdir"] = "\"" + os.path.dirname(program) + "\""
        vdf_data["shortcuts"][shortcut_id] = shortcut_data
        # write data to shortcuts_path
        shortcuts_path.write_bytes(vdf.binary_dumps(vdf_data))
        exit(0)

